import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import Layout from '../Components/Layout';
import "../assets/css/Aboutus.css";
import NavbarHome from '../Components/NavbarHome';
import { useNavigate } from 'react-router-dom';

const Aboutus = () => {
  return (
    <div className='body2'>
    <div className="card-10">
   <h2>ABOUT US</h2><br/>
   <h1>Brief History Of Insurance</h1><br/>
   
  <p>The story of insurance is probably as old as the story of mankind. The same instinct that prompts modern businessmen today to secure themselves against loss and disaster existed in primitive men also. They too sought to avert the evil consequences of fire and flood and loss of life and were willing to make some sort of sacrifice in order to achieve security. Though the concept of insurance is largely a development of the recent past, particularly after the industrial era – past few centuries – yet its beginnings date back almost 6000 years.</p><br/>
  <p>Life Insurance in its modern form came to India from England in the year 1818. Oriental Life Insurance Company started by Europeans in Calcutta was the first life insurance company on Indian Soil. All the insurance companies established during that period were brought up with the purpose of looking after the needs of European community and Indian natives were not being insured by these companies. However, later with the efforts of eminent people like Babu Muttylal Seal, the foreign life insurance companies started insuring Indian lives. But Indian lives were being treated as sub-standard lives and heavy extra premiums were being charged on them. Bombay Mutual Life Assurance Society heralded the birth of first Indian life insurance company in the year 1870, and covered Indian lives at normal rates. Starting as Indian enterprise with highly patriotic motives, insurance companies came into existence to carry the message of insurance and social security through insurance to various sectors of society. Bharat Insurance Company (1896) was also one of such companies inspired by nationalism. The Swadeshi movement of 1905-1907 gave rise to more insurance companies. The United India in Madras, National Indian and National Insurance in Calcutta and the Co-operative Assurance at Lahore were established in 1906. In 1907, Hindustan Co-operative Insurance Company took its birth in one of the rooms of the Jorasanko, house of the great poet Rabindranath Tagore, in Calcutta. The Indian Mercantile, General Assurance and Swadeshi Life (later Bombay Life) were some of the companies established during the same period. Prior to 1912 India had no legislation to regulate insurance business. In the year 1912, the Life Insurance Companies Act, and the Provident Fund Act were passed. The Life Insurance Companies Act, 1912 made it necessary that the premium rate tables and periodical valuations of companies should be certified by an actuary. But the Act discriminated between foreign and Indian companies on many accounts, putting the Indian companies at a disadvantage.</p><br/>
  <p>Life Insurance Corporation continues to be the dominant life insurer even in the liberalized scenario of Indian insurance and is moving fast on a new growth trajectory surpassing its own past records. Life Insurance Corporation has issued over one crore policies during the current year. It has crossed the milestone of issuing 1,01,32,955 new policies by 15th Oct, 2005, posting a healthy growth rate of 16.67% over the corresponding period of the previous year.</p><br/>
 <p>From then to now, Life Insurance Corporation has crossed many milestones and has set unprecedented performance records in various aspects of life insurance business. The same motives which inspired our forefathers to bring insurance into existence in this country inspire us at Life Insurance Corporation to take this message of protection to light the lamps of security in as many homes as possible and to help the people in providing security to their families.</p><br/>
 <p>The first two decades of the twentieth century saw lot of growth in insurance business. From 44 companies with total business-in-force as Rs.22.44 crore, it rose to 176 companies with total business-in-force as Rs.298 crore in 1938. During the mushrooming of insurance companies many financially unsound concerns were also floated which failed miserably. The Insurance Act 1938 was the first legislation governing not only life insurance but also non-life insurance to provide strict state control over insurance business. The demand for nationalization of life insurance industry was made repeatedly in the past but it gathered momentum in 1944 when a bill to amend the Life Insurance Act 1938 was introduced in the Legislative Assembly. However, it was much later on the 19th of January, 1956, that life insurance in India was nationalized. About 154 Indian insurance companies, 16 non-Indian companies and 75 provident were operating in India at the time of nationalization. Nationalization was accomplished in two stages; initially the management of the companies was taken over by means of an Ordinance, and later, the ownership too by means of a comprehensive bill. The Parliament of India passed the Life Insurance Corporation Act on the 19th of June 1956, and the Life Insurance Corporation of India was created on 1st September, 1956, with the objective of spreading life insurance much more widely and in particular to the rural areas with a view to reach all insurable persons in the country, providing them adequate financial cover at a reasonable cost.
</p><br/>
<h8>THANK YOU</h8>
 </div>
 </div>
  );
}

export default Aboutus;